#!/bin/bash
set -e

if [ -x "$(command -v apt-get)" ]; then
  gomplate < "/etc/php/${PHP_VERSION}/mods-available/docker.ini.template" \
    | sudo tee "/etc/php/${PHP_VERSION}/mods-available/docker.ini"
  gomplate < "/etc/php/${PHP_VERSION}/mods-available/opcache.ini.template" \
    | sudo tee "/etc/php/${PHP_VERSION}/mods-available/opcache.ini"
  if [ -f "/etc/php/${PHP_VERSION}/mods-available/xdebug.ini.template" ]; then
    gomplate < "/etc/php/${PHP_VERSION}/mods-available/xdebug.ini.template" \
      | sudo tee "/etc/php/${PHP_VERSION}/mods-available/xdebug.ini"
  fi
  if [ -f "/etc/php/${PHP_VERSION}/mods-available/blackfire.ini.template" ]; then
    gomplate < "/etc/php/${PHP_VERSION}/mods-available/blackfire.ini.template" \
      | sudo tee "/etc/php/${PHP_VERSION}/mods-available/blackfire.ini"
  fi
  if [ -f "/etc/php-cli.ini.template" ]; then
    gomplate < "/etc/php-cli.ini.template" \
      | sudo tee "/etc/php-cli.ini"
  fi
  if [ -f /etc/ssl/reward-rootca-cert/ca.cert.pem ]; then
    sudo cp /etc/ssl/reward-rootca-cert/ca.cert.pem /usr/local/share/ca-certificates/reward-rootca-cert.pem
  fi
  sudo phpenmod docker
  sudo phpenmod opcache
  sudo phpenmod xdebug
  sudo phpenmod blackfire
  sudo update-ca-certificates
  sudo cron
elif [ -x "$(command -v dnf)" ] || [ -x "$(command -v yum)" ]; then
  gomplate < /etc/php.d/docker.ini.template \
    | sudo tee /etc/php.d/01-docker.ini
  gomplate < /etc/php.d/opcache.ini.template \
    | sudo tee /etc/php.d/01-opcache.ini
  if [ -f "/etc/php.d/xdebug.ini.template" ]; then
    gomplate < "/etc/php.d/xdebug.ini.template" \
      | sudo tee "/etc/php.d/15-xdebug.ini"
  fi
  if [ -f "/etc/php.d/blackfire.ini.template" ]; then
    gomplate < "/etc/php.d/blackfire.ini.template" \
      | sudo tee "/etc/php.d/10-blackfire.ini"
  fi
  if [ -f "/etc/php-cli.ini.template" ]; then
    gomplate < "/etc/php-cli.ini.template" \
      | sudo tee "/etc/php-cli.ini"
  fi
  if [ -f /etc/ssl/reward-rootca-cert/ca.cert.pem ]; then
    sudo cp /etc/ssl/reward-rootca-cert/ca.cert.pem /etc/pki/ca-trust/source/anchors/reward-rootca-cert.pem
  fi
  sudo update-ca-trust
  sudo crond
fi

# start socat process in background to connect sockets used for agent access within container environment
# shellcheck disable=SC2039
if [ -S /run/host-services/ssh-auth.sock ] && [ "${SSH_AUTH_SOCK}" != "/run/host-services/ssh-auth.sock" ]; then
  sudo bash -c "nohup socat UNIX-CLIENT:/run/host-services/ssh-auth.sock \
    UNIX-LISTEN:${SSH_AUTH_SOCK},fork,user=www-data,group=www-data 1>/var/log/socat-ssh-auth.log 2>&1 &"
fi

# install requested node version if not already installed
NODE_INSTALLED="$(node -v | perl -pe 's/^v([0-9]+)\..*$/$1/')";
if [ "${NODE_INSTALLED}" -ne "${NODE_VERSION}" ] || [ "${NODE_VERSION}" = "latest" ] || [ "${NODE_VERSION}" = "lts" ]; then
  sudo n "${NODE_VERSION}"
fi

# Configure composer version
if [ "${COMPOSER_VERSION:-}" = "1" ]; then
  sudo alternatives --set composer /usr/bin/composer1
elif [ "${COMPOSER_VERSION:-}" = "2" ]; then
  sudo alternatives --set composer /usr/bin/composer2
fi

# Resolve permission issues with directories auto-created by volume mounts; to use set CHOWN_DIR_LIST to
# a list of directories (relative to working directory) to chown, walking up the paths to also chown each
# specified parent directory. Example: "dir1/dir2 dir3" will chown dir1/dir2, then dir1 followed by dir3
# shellcheck disable=SC2039
for DIR in ${CHOWN_DIR_LIST:-}; do
  if [ -d "${DIR}" ]; then
    while :; do
      sudo chown www-data:www-data "${DIR}"
      DIR=$(dirname "${DIR}")
      if [ "${DIR}" = "." ] || [ "${DIR}" = "/" ]; then
        break;
      fi
    done
  fi
done

# Resolve permission issue with /var/www/html being owned by root as a result of volume mounted on php-fpm
# and nginx combined with nginx running as a different uid/gid than php-fpm does. This condition, when it
# surfaces would cause mutagen sync failures (on initial startup) on macOS environments.
sudo chown www-data:www-data /var/www/html

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
  set -- php-fpm "$@"
fi

exec "$@"
