{{- /* @formatter:off */ -}}

x-volumes: &volumes
  - .{{ default "" .reward_web_root }}/wp-content/uploads:/var/www/html/wp-content/uploads:cached
  - appdata:/var/www/html

x-environment: &environment
  - CHOWN_DIR_LIST=wp-content/uploads

services:
  nginx: { volumes: *volumes }
  php-fpm: { volumes: *volumes, environment: *environment }
  php-debug: { volumes: *volumes, environment: *environment }

volumes:
  appdata:
