version: "2"
run:
  concurrency: 8
  modules-download-mode: readonly
  tests: true
  allow-parallel-runners: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - ireturn
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nlreturn
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - staticcheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
  disable:
    - bodyclose
    - contextcheck
    - exhaustruct
    - gochecknoglobals
    - nilerr
    - noctx
    - nonamedreturns
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - tparallel
    - wastedassign
  settings:
    funlen:
      lines: 100
    goconst:
      min-occurrences: 5
    staticcheck:
      checks:
        - -SA5008
        - all
    varnamelen:
      max-distance: 15
      ignore-names:
        - tt
        - id
      ignore-decls:
        - t table.Writer
        - bs []byte
        - bs bytes.Buffer
        - i int
        - FS *afero.Afero
    wrapcheck:
      ignore-package-globs:
        - github.com/rewardenv/reward/*
    wsl:
      allow-assign-and-anything: true
      allow-trailing-comment: true
      allow-separated-leading-comment: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - docs/*
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - staticcheck
        text: "QF1008:"
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - docs/*
      - third_party$
      - builtin$
      - examples$
