---
version: 2
project_name: reward
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/reward
    ldflags:
      - -s -w -X main.VERSION={{.Tag}}+{{ time "200601021504" }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"
archives:
  - format: binary
release:
  extra_files:
    - glob: ./VERSION.txt
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^deps'
