[default.extend-identifiers]
# https://manpages.debian.org/bookworm/manpages-dev/open.2.en.html#File_access_mode
"O_WRONLY" = "O_WRONLY"

[files]
extend-exclude = [
  "docs/configuration/xdebug.md",
  "go.mod",
  "go.sum"
]
