FROM centos:7

RUN yum install -y \
    ca-certificates \
    sudo \
    openssh-clients

COPY build/reward-linux /usr/bin/reward

RUN echo "DEBUG: true" > /root/.reward.yml

ENTRYPOINT ["/usr/bin/reward"]
