{{- /* @formatter:off */ -}}

services:
  php-fpm:
    depends_on:
      - checkoutdb

  php-debug:
    depends_on:
      - checkoutdb

{{- if ( default false .reward_spx ) }}
  php-spx:
    depends_on:
      - checkoutdb
{{- end }}

  checkoutdb:
    hostname: "{{ .reward_env_name }}-checkoutdb"
    image: {{ default "docker.io/rewardenv" .reward_docker_image_repo }}/mariadb:{{ default "10.4" .mariadb_version }}
    labels:
      - dev.reward.container.name=checkoutdb
      - dev.reward.environment.name={{ .reward_env_name }}
    environment:
      - MYSQL_ROOT_PASSWORD={{ default "magento" .mysql_root_password }}
      - MYSQL_DATABASE={{ default "magento" .mysql_database }}
      - MYSQL_USER={{ default "magento" .mysql_user }}
      - MYSQL_PASSWORD={{ default "magento" .mysql_password }}
    command:
      - mysqld
      - --max_allowed_packet=1024M
    volumes:
      - checkoutdbdata:/var/lib/mysql

volumes:
  checkoutdbdata:
