{{- /* @formatter:off */ -}}

x-volumes: &volumes
{{ if isEnabled .reward_sync_enabled }}
  - .{{ default "" .reward_web_root }}/pub/media:/var/www/html/pub/media:cached
  - appdata:/var/www/html
{{ else }}
  - .{{ default "" .reward_web_root }}/:/var/www/html
{{ end }}

x-environment: &environment
  - CHOWN_DIR_LIST=pub/media

services:
  php-blackfire: { volumes: *volumes, environment: *environment }
