version: "3.5"
services:
  php-fpm:
    depends_on:
      - db

  db:
    hostname: "{{.reward_env_name}}-mariadb"
    image: {{default "docker.io/rewardenv" .reward_docker_image_repo}}/mariadb:{{default "10.4" .mariadb_version}}
    environment:
      - MYSQL_ROOT_PASSWORD={{default "app" .mysql_root_password}}
      - MYSQL_DATABASE={{default "app" .mysql_database}}
      - MYSQL_USER={{default "app" .mysql_user}}
      - MYSQL_PASSWORD={{default "app" .mysql_password}}
    volumes:
      - dbdata:/var/lib/mysql
    command:
      - mysqld
      - --max_allowed_packet=1024M
      - --explicit_defaults_for_timestamp=on
{{if ge 10.5 (float64 .mariadb_version)}}
      - --log-bin-trust-function-creators=on
{{end}}
{{if eq (default "" .mysql_character_set_server) ""}}
      - --character-set-server=utf8mb4
{{else}}
      - --character-set-server={{.mysql_character_set_server}}
{{end}}
{{if eq (default "" .mysql_collation_server) ""}}
      - --collation-server=utf8mb4_unicode_ci
{{else}}
      - --collation-server={{.mysql_collation_server}}
{{end}}
{{if isEnabledStrict .mysql_disable_strict_mode}}
      - --sql-mode=
      - --innodb_strict_mode=OFF
{{end}}


volumes:
  dbdata:
