{{- /* @formatter:off */ -}}

version: "3.5"
services:
{{ if not (eq "pwa-studio" .reward_env_type) }}
{{ if not (isEnabledStrict .reward_single_web_container) }}
  nginx:
    labels:
      - traefik.enable=false
      - traefik.http.routers.{{ .reward_env_name }}-nginx.priority=2
{{ else }}
  php-fpm:
    labels:
      - traefik.enable=false
      - traefik.http.routers.{{ .reward_env_name }}-php-fpm.priority=2
{{ end }}
{{ else }}
  node:
    labels:
      - traefik.enable=false
      - traefik.http.routers.{{ .reward_env_name }}-node.priority=2
{{ end }}

  varnish:
    hostname: "{{ .reward_env_name }}-varnish"
    image: {{ default "docker.io/rewardenv" .reward_docker_image_repo }}/varnish:{{ default "6.0" .varnish_version }}
    env_file:
      - .env
{{ if not (eq "pwa-studio" .reward_env_type) }}
{{ if not (isEnabledStrict .reward_single_web_container) }}
{{ if and ( eq "darwin" .reward_runtime_os ) ( eq "arm64" .reward_runtime_arch ) }}
    environment:
      - VMOD_DYNAMIC_ENABLED=false
{{ end }}
    depends_on:
      - nginx
{{ else }}
    environment:
      - BACKEND_HOST=php-fpm
{{ if and ( eq "darwin" .reward_runtime_os ) ( eq "arm64" .reward_runtime_arch ) }}
      - VMOD_DYNAMIC_ENABLED=false
{{ end }}
    depends_on:
      - php-fpm
{{ end }}
{{ else }}
    environment:
      - BACKEND_HOST=node
      - BACKEND_PORT=8000
{{ if and ( eq "darwin" .reward_runtime_os ) ( eq "arm64" .reward_runtime_arch ) }}
      - VMOD_DYNAMIC_ENABLED=false
{{ end }}
    depends_on:
      - node
{{ end }}
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ .reward_env_name }}-varnish.tls=true
      - traefik.http.routers.{{ .reward_env_name }}-varnish.priority=9
      - traefik.http.routers.{{ .reward_env_name }}-varnish.rule=
          HostRegexp(`{subdomain:.+}.{{ .traefik_domain }}`) || Host(`{{ .traefik_domain }}`)
      - traefik.http.services.{{ .reward_env_name }}-varnish.loadbalancer.server.port=80
      - dev.reward.container.name=varnish
      - dev.reward.environment.name={{ .reward_env_name }}
