{{- /* @formatter:off */ -}}

x-volumes: &volumes
  - .{{ default "" $.reward_web_root }}/public/media:/var/www/html/public/media:cached
  - appdata:/var/www/html

x-environment: &environment
  - CHOWN_DIR_LIST=public/media

services:
{{ if not ( isEnabled ( default false $.reward_single_web_container )) }}
  nginx: { volumes: *volumes }
{{ end }}
  php-fpm: { volumes: *volumes, environment: *environment }
  php-debug: { volumes: *volumes, environment: *environment }
{{- if ( default false $.reward_spx ) }}
  php-spx: { volumes: *volumes, environment: *environment }
{{- end }}

volumes:
  appdata:
