# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reward < Formula
  desc "Reward is CLI utility for orchestrating Docker based development environments."
  homepage ""
  version "0.1.0-beta"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rewardenv/reward/releases/download/v0.1.0-beta/reward_Darwin_x86_64.tar.gz"
    sha256 "53dd0512e774d80d2b087eb90f5b18e187b630110c98bb606237719e3dbb558a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/rewardenv/reward/releases/download/v0.1.0-beta/reward_Linux_x86_64.tar.gz"
    sha256 "4d771334d924f5529a5b188e6e09fddafbaac8896c96bde4c5656e9dc3b8a9b7"
  end

  depends_on "docker" => :optional
  depends_on "docker-edge" => :optional
  depends_on "mutagen" => :optional

  def install
    bin.install "reward"
  end
end
