{{- /* @formatter:off */ -}}

networks:
  default:
    name: {{ $.reward_env_name }}
    labels:
      - dev.reward.environment.name={{ $.reward_env_name }}
      - dev.reward.environment.type={{ $.reward_env_type }}
