{{- /* @formatter:off */ -}}

{{ if not ( isEnabledDefault $ "reward_single_web_container" false ) }}
services:
  nginx:
    environment:
      - XDEBUG_CONNECT_BACK_HOST={{ default "host.docker.internal" $.xdebug_connect_back_host }}
{{ end }}
