{{- /* @formatter:off */ -}}

{{ if not ( isEnabled ( default false .reward_single_web_container )) }}
services:
  nginx:
    environment:
      - XDEBUG_CONNECT_BACK_HOST={{ default "host.docker.internal" .xdebug_connect_back_host }}
{{ end }}
