{{- /* @formatter:off */ -}}

x-extra_hosts: &extra_hosts
  - {{ .traefik_domain }}:{{ default "0.0.0.0" .traefik_address }}
  - {{ default "app" .traefik_subdomain }}.{{ .traefik_domain }}:{{ default "0.0.0.0" .traefik_address }}
{{ if .traefik_extra_hosts }}
{{ $traefik_address := default "0.0.0.0" .traefik_address }}
{{ range (splitList " " .traefik_extra_hosts) }}
  - {{ . }}:{{ $traefik_address }}
{{ end }}
{{ end }}

services:
  node:
    hostname: "{{ .reward_env_name }}-node"
    image: {{ default "docker.io/rewardenv" .reward_docker_image_repo }}/node:{{ default "16" .node_version }}
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ .reward_env_name }}-node.tls=true
{{- if .reward_traefik_allow_http }}
      - traefik.http.routers.{{ .reward_env_name }}-node-http.priority=2
      - traefik.http.routers.{{ .reward_env_name }}-node-http.rule=
        HostRegexp(`{subdomain:.+}.{{ .traefik_domain }}`) || Host(`{{ .traefik_domain }}`)
      - traefik.http.routers.{{ .reward_env_name }}-node-http.service={{ .reward_env_name }}-node
{{- end }}
      - traefik.http.routers.{{ .reward_env_name }}-node.priority=2
      - traefik.http.routers.{{ .reward_env_name }}-node.rule=
          HostRegexp(`{subdomain:.+}.{{ .traefik_domain }}`) || Host(`{{ .traefik_domain }}`)
      - traefik.http.services.{{ .reward_env_name }}-node.loadbalancer.server.port=8000
      - traefik.docker.network={{ .reward_env_name }}
      - dev.reward.container.name=node
      - dev.reward.environment.name={{ .reward_env_name }}
    volumes:
      - {{ .reward_ssh_dir }}:/home/node/.ssh:cached
      - .{{ default "" .reward_web_root }}/:/usr/src/app:cached
    extra_hosts: *extra_hosts
