{{- /* @formatter:off */ -}}

x-volumes: &volumes
  - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock

services:
  php-fpm:
{{ if isEnabled ( default false .reward_single_web_container) }}
    environment:
      - XDEBUG_CONNECT_BACK_HOST={{ default "host.docker.internal" .xdebug_connect_back_host }}
{{ end }}
    volumes: *volumes
  php-debug: { volumes: *volumes }
{{- if ( default false .reward_spx ) }}
  php-spx: { volumes: *volumes }
{{- end }}
