{{- /* @formatter:off */ -}}

x-volumes: &volumes
  - {{ default "/dev/null" .ssh_auth_sock }}:/run/host-services/ssh-auth.sock

services:
  php-fpm: { volumes: *volumes }
  php-debug: { volumes: *volumes }
