{{- /* @formatter:off */ -}}

services:
  redis:
    hostname: "{{ $.reward_env_name }}-redis"
    image: {{ default "docker.io/rewardenv" $.reward_docker_image_repo }}/redis:{{ default "6.0" $.redis_version }}
    labels:
      - dev.reward.container.name=redis
      - dev.reward.environment.name={{ $.reward_env_name }}
    volumes:
      - redis:/data
{{- if isEnabled ( default false $.redis_expose ) }}
    ports:
      - {{ default 6379 $.redis_expose_target }}:6379
{{- end }}

volumes:
  redis:
