{{- /* @formatter:off */ -}}

services:
{{- if not ( isEnabledDefault $ "reward_single_web_container" false ) }}
  nginx: {}
{{ end }}

  php-fpm: {}

  php-debug: {}

{{- if ( default false $.reward_spx ) }}
  php-spx: { }
{{- end }}
