{{- /* @formatter:off */ -}}

services:
{{- if not ( isEnabled ( default false $.reward_single_web_container )) }}
  nginx: {}
{{ end }}

  php-fpm: {}

  php-debug: {}

{{- if ( default false $.reward_spx ) }}
  php-spx: { }
{{- end }}
