{{- /* @formatter:off */ -}}

{{ if isEnabled $.reward_sync_enabled }}
x-volumes: &volumes
  - .{{ default "" $.reward_web_root }}/media:/var/www/html/media:cached
  - appdata:/var/www/html
{{ end }}

x-environment: &environment
  - CHOWN_DIR_LIST=media

services:
{{- if not ( isEnabled ( default false $.reward_single_web_container )) }}
  nginx: { volumes: *volumes }
{{ end }}
  php-fpm: { volumes: *volumes, environment: *environment }
  php-debug: { volumes: *volumes, environment: *environment }
{{- if ( default false $.reward_spx ) }}
  php-spx: { volumes: *volumes, environment: *environment }
{{- end }}

volumes:
  appdata:
