{{- /* @formatter:off */ -}}

services:
{{- if not ( isEnabled ( default false $.reward_single_web_container )) }}
  nginx:
    environment:
      - NGINX_TEMPLATE=magento1.conf
{{ end }}

  php-fpm:
    environment:
      - MAGE_IS_DEVELOPER_MODE=1

  php-debug:
    environment:
      - MAGE_IS_DEVELOPER_MODE=1

{{- if ( default false $.reward_spx ) }}
  php-spx:
    environment:
      - MAGE_IS_DEVELOPER_MODE=1
{{- end }}
