{{- /* @formatter:off */ -}}

{{ if isEnabled $.reward_sync_enabled }}
x-volumes: &volumes
  - .{{ default "" $.reward_web_root }}/media:/var/www/html/media:cached
  - appdata:/var/www/html
{{ end }}

x-environment: &environment
  - CHOWN_DIR_LIST=media

services:
  php-blackfire: { volumes: *volumes, environment: *environment }
