# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "PHP Chain 05 Apps • Docker Build"
on:
  schedule:
    - cron: "0 6 * * 6"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/php/.trigger
    branches:
      - main
      - feature/revamp-php-build

jobs:
  php-fpm-rootless-magento1-apps:
    uses: ./.github/workflows/docker-build-php-fpm-rootless-magento1-apps.yml
    secrets: inherit

  php-fpm-rootless-magento2-apps:
    uses: ./.github/workflows/docker-build-php-fpm-rootless-magento2-apps.yml
    secrets: inherit

  php-fpm-rootless-shopware-apps:
    uses: ./.github/workflows/docker-build-php-fpm-rootless-shopware-apps.yml
    secrets: inherit

  php-fpm-rootless-wordpress-apps:
    uses: ./.github/workflows/docker-build-php-fpm-rootless-wordpress-apps.yml
    secrets: inherit

  phase6:
    runs-on: ubuntu-latest
    needs:
      - php-fpm-rootless-magento1-apps
      - php-fpm-rootless-magento2-apps
      - php-fpm-rootless-shopware-apps
      - php-fpm-rootless-wordpress-apps
    steps:
      - run: 'true'

  php-fpm-magento1-apps:
    needs: [phase6]
    uses: ./.github/workflows/docker-build-php-fpm-magento1-apps.yml
    secrets: inherit

  php-fpm-magento2-apps:
    needs: [phase6]
    uses: ./.github/workflows/docker-build-php-fpm-magento2-apps.yml
    secrets: inherit

  php-fpm-shopware-apps:
    needs: [phase6]
    uses: ./.github/workflows/docker-build-php-fpm-shopware-apps.yml
    secrets: inherit

  php-fpm-wordpress-apps:
    needs: [phase6]
    uses: ./.github/workflows/docker-build-php-fpm-wordpress-apps.yml
    secrets: inherit
