# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "PHP-FPM Magento 1 • Docker Build"
on:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/template-docker-build-php-app.yml
    secrets: inherit
    with:
      app_name: "magento1"
      rootless: false
