# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "PHP Chain 01 • Docker Build"
on:
  schedule:
    - cron: "0 3 * * 6"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/php/.trigger
    branches:
      - main
      - feature/revamp-php-build

jobs:
  php-cli:
    uses: ./.github/workflows/docker-build-php-cli.yml
    secrets: inherit

  php-cli-loaders:
    needs: [php-cli]
    uses: ./.github/workflows/docker-build-php-cli-loaders.yml
    secrets: inherit

  php-fpm:
    needs: [php-cli]
    uses: ./.github/workflows/docker-build-php-fpm.yml
    secrets: inherit

  php-fpm-loaders:
    needs: [php-fpm]
    uses: ./.github/workflows/docker-build-php-fpm-loaders.yml
    secrets: inherit

  phase1:
    runs-on: ubuntu-latest
    needs:
      - php-cli
      - php-cli-loaders
      - php-fpm
      - php-fpm-loaders
    steps:
      - run: 'true'

  php-fpm-base:
    needs: [phase1]
    uses: ./.github/workflows/docker-build-php-fpm-base.yml
    secrets: inherit

  php-fpm-magento1:
    needs: [php-fpm-base]
    uses: ./.github/workflows/docker-build-php-fpm-magento1.yml
    secrets: inherit

  php-fpm-magento2:
    needs: [php-fpm-base]
    uses: ./.github/workflows/docker-build-php-fpm-magento2.yml
    secrets: inherit

  php-fpm-shopware:
    needs: [php-fpm-base]
    uses: ./.github/workflows/docker-build-php-fpm-shopware.yml
    secrets: inherit

  php-fpm-wordpress:
    needs: [php-fpm-base]
    uses: ./.github/workflows/docker-build-php-fpm-wordpress.yml
    secrets: inherit
