# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "Elasticsearch • Docker Build"
on:
  schedule:
    - cron: "0 1 * * 6"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/elasticsearch/**
      - .github/workflows/docker-build-elasticsearch.yml
    branches:
      - main

jobs:
  elasticsearch:
    uses: ./.github/workflows/_service-build.yml
    secrets: inherit
    with:
      service: elasticsearch
      builds: |
        [
          {
            "build_tag": "latest",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "9.0.2"
            }
          },
          {
            "build_tag": "9.0",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "9.0.2"
            }
          },
          {
            "build_tag": "8.18",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "8.18.2"
            }
          },
          {
            "build_tag": "8.17",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "8.17.6"
            }
          }
        ]
