# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "Dnsmasq • Docker Build"
on:
  schedule:
    - cron: "0 1 * * 6"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/dnsmasq/**
      - .github/workflows/docker-build-dnsmasq.yml
    branches:
      - main

jobs:
  dnsmasq:
    uses: ./.github/workflows/_service-build.yml
    secrets: inherit
    with:
      service: dnsmasq
      builds: |
        [
          {
            "build_tag": "latest",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "latest"
            }
          }
        ]
