# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "MariaDB • Docker Build"
on:
  schedule:
    - cron: "0 1 * * 6"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/mariadb/**
      - .github/workflows/docker-build-mariadb.yml
    branches:
      - main

jobs:
  mariadb:
    uses: ./.github/workflows/_service-build.yml
    secrets: inherit
    with:
      service: mariadb
      builds: |
        [
          {
            "build_tag": "latest",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "11.8"
            }
          },
          {
            "build_tag": "11.8",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "11.8"
            }
          },
          {
            "build_tag": "11.4",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "11.4"
            }
          },
          {
            "build_tag": "10.11",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "10.11"
            }
          },
          {
            "build_tag": "10.6",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "10.6"
            }
          }
        ]
