# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "PHP Chain 03 Web • Docker Build"
on:
  schedule:
    - cron: "0 4 * * 6"
  workflow_dispatch:

jobs:
  php-fpm-rootless-magento2-web:
    uses: ./.github/workflows/docker-build-php-fpm-rootless-magento2-web.yml
    secrets: inherit

  php-fpm-rootless-shopware-web:
    uses: ./.github/workflows/docker-build-php-fpm-rootless-shopware-web.yml
    secrets: inherit

  php-fpm-rootless-wordpress-web:
    uses: ./.github/workflows/docker-build-php-fpm-rootless-wordpress-web.yml
    secrets: inherit

  phase1:
    runs-on: ubuntu-latest
    needs:
      - php-fpm-rootless-magento2-web
      - php-fpm-rootless-shopware-web
      - php-fpm-rootless-wordpress-web
    steps:
      - run: 'true'

  php-fpm-magento2-web:
    needs: [ phase1 ]
    uses: ./.github/workflows/docker-build-php-fpm-magento2-web.yml
    secrets: inherit

  php-fpm-shopware-web:
    needs: [ phase1 ]
    uses: ./.github/workflows/docker-build-php-fpm-shopware-web.yml
    secrets: inherit

  php-fpm-wordpress-web:
    needs: [ phase1 ]
    uses: ./.github/workflows/docker-build-php-fpm-wordpress-web.yml
    secrets: inherit

  phase2:
    runs-on: ubuntu-latest
    needs:
      - php-fpm-magento2-web
      - php-fpm-shopware-web
      - php-fpm-wordpress-web
    steps:
      - run: 'true'

  php-fpm-rootless-magento2-web-apps:
    needs: [ phase2 ]
    uses: ./.github/workflows/docker-build-php-fpm-rootless-magento2-web-apps.yml
    secrets: inherit

  php-fpm-rootless-shopware-web-apps:
    needs: [ phase2 ]
    uses: ./.github/workflows/docker-build-php-fpm-rootless-shopware-web-apps.yml
    secrets: inherit

  php-fpm-rootless-wordpress-web-apps:
    needs: [ phase2 ]
    uses: ./.github/workflows/docker-build-php-fpm-rootless-wordpress-web-apps.yml
    secrets: inherit

  phase3:
    runs-on: ubuntu-latest
    needs:
      - php-fpm-rootless-magento2-web-apps
      - php-fpm-rootless-shopware-web-apps
      - php-fpm-rootless-wordpress-web-apps
    steps:
      - run: 'true'

  php-fpm-magento2-web-apps:
    needs: [ phase3 ]
    uses: ./.github/workflows/docker-build-php-fpm-magento2-web-apps.yml
    secrets: inherit

  php-fpm-shopware-web-apps:
    needs: [ phase3 ]
    uses: ./.github/workflows/docker-build-php-fpm-shopware-web-apps.yml
    secrets: inherit

  php-fpm-wordpress-web-apps:
    needs: [ phase3 ]
    uses: ./.github/workflows/docker-build-php-fpm-wordpress-web-apps.yml
    secrets: inherit
