# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "PHP-FPM Rootless Xdebug2 • Docker Build"
on:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/template-docker-build-php-app.yml
    secrets: inherit
    with:
      app_name: "xdebug3"
      rootless: true
      php_version: '[ "5.6", "7.0", "7.1", "7.2", "7.3", "7.4" ]'
