# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "Mailbox (mailpit) • Docker Build"
on:
  schedule:
    - cron: "0 1 * * 6"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/mailbox/**
      - .github/workflows/docker-build-mailbox.yml
    branches:
      - main

jobs:
  mailbox:
    uses: ./.github/workflows/_service-build.yml
    secrets: inherit
    with:
      service: mailbox
      builds: |
        [
          {
            "build_tag": "latest",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "v1.26"
            }
          },
          {
            "build_tag": "1.26",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "v1.26"
            }
          }
        ]
