# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "MariaDB • Docker Build"
on:
  schedule:
    - cron: "0 1 * * 6"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/mariadb/**
    branches:
      - main
jobs:
  build:
    name: "Build mariadb"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - BUILD_TAG: "latest"
            IMAGE_TAG: "11.4"
          - BUILD_TAG: "11.4"
            IMAGE_TAG: "11.4"
          - BUILD_TAG: "11.3"
            IMAGE_TAG: "11.3"
          - BUILD_TAG: "11.2"
            IMAGE_TAG: "11.2"
          - BUILD_TAG: "11.1"
            IMAGE_TAG: "11.1"
          - BUILD_TAG: "11.0"
            IMAGE_TAG: "11.0"
          - BUILD_TAG: "10.11"
            IMAGE_TAG: "10.11"
          - BUILD_TAG: "10.10"
            IMAGE_TAG: "10.10"
          - BUILD_TAG: "10.9"
            IMAGE_TAG: "10.9"
          - BUILD_TAG: "10.8"
            IMAGE_TAG: "10.8"
          - BUILD_TAG: "10.7"
            IMAGE_TAG: "10.7"
          - BUILD_TAG: "10.6"
            IMAGE_TAG: "10.6"
          - BUILD_TAG: "10.5"
            IMAGE_TAG: "10.5"
          - BUILD_TAG: "10.4"
            IMAGE_TAG: "10.4"
          - BUILD_TAG: "10.3"
            IMAGE_TAG: "10.3"
          - BUILD_TAG: "10.2"
            IMAGE_TAG: "10.2"
          - BUILD_TAG: "10.1"
            IMAGE_TAG: "10.1"
          - BUILD_TAG: "10.0"
            IMAGE_TAG: "10.0"
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: mirror.gcr.io/tonistiigi/binfmt:latest

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
          config-inline: |
            [registry."docker.io"]
              mirrors = ["${{ secrets.DOCKER_PROXY }}"]

      - uses: supplypike/setup-bin@v4
        with:
          uri: https://github.com/hairyhenderson/gomplate/releases/latest/download/gomplate_linux-amd64
          name: gomplate
          version: latest

      - name: Generate Dockerfile
        run: gomplate -f images/mariadb/tpl.Dockerfile -o images/mariadb/Dockerfile
        env:
          IMAGE_TAG: ${{ matrix.IMAGE_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: images/mariadb/context
          file: images/mariadb/Dockerfile
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ vars.DOCKER_REPO }}/mariadb:${{ matrix.BUILD_TAG }}
          cache-from: type=registry,ref=${{ vars.DOCKER_REPO }}/mariadb:${{ matrix.BUILD_TAG }}
          cache-to: type=inline
