# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "Elasticsearch • Docker Build"
on:
  schedule:
    - cron: "0 1 * * 6"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/elasticsearch/**
    branches:
      - main
jobs:
  build:
    name: "Build elasticsearch"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - BUILD_TAG: "latest"
            IMAGE_TAG: "8.17.4"
          - BUILD_TAG: "8.16"
            IMAGE_TAG: "8.16.6"
          - BUILD_TAG: "8.15"
            IMAGE_TAG: "8.15.5"
          - BUILD_TAG: "8.14"
            IMAGE_TAG: "8.14.3"
          - BUILD_TAG: "8.13"
            IMAGE_TAG: "8.13.4"
          - BUILD_TAG: "8.12"
            IMAGE_TAG: "8.12.2"
          - BUILD_TAG: "8.11"
            IMAGE_TAG: "8.11.4"
          - BUILD_TAG: "8.10"
            IMAGE_TAG: "8.10.4"
          - BUILD_TAG: "8.9"
            IMAGE_TAG: "8.9.2"
          - BUILD_TAG: "8.8"
            IMAGE_TAG: "8.8.2"
          - BUILD_TAG: "8.7"
            IMAGE_TAG: "8.7.1"
          - BUILD_TAG: "8.6"
            IMAGE_TAG: "8.6.2"
          - BUILD_TAG: "8.5"
            IMAGE_TAG: "8.5.3"
          - BUILD_TAG: "8.4"
            IMAGE_TAG: "8.4.3"
          - BUILD_TAG: "8.3"
            IMAGE_TAG: "8.3.3"
          - BUILD_TAG: "8.2"
            IMAGE_TAG: "8.2.3"
          - BUILD_TAG: "8.1"
            IMAGE_TAG: "8.1.3"
          - BUILD_TAG: "8.0"
            IMAGE_TAG: "8.0.1"
          - BUILD_TAG: "7.17"
            IMAGE_TAG: "7.17.28"
          - BUILD_TAG: "7.16"
            IMAGE_TAG: "7.16.3"
          - BUILD_TAG: "7.15"
            IMAGE_TAG: "7.15.1"
          - BUILD_TAG: "7.14"
            IMAGE_TAG: "7.14.2"
          - BUILD_TAG: "7.13"
            IMAGE_TAG: "7.13.4"
          - BUILD_TAG: "7.12"
            IMAGE_TAG: "7.12.1"
          - BUILD_TAG: "7.11"
            IMAGE_TAG: "7.11.2"
          - BUILD_TAG: "7.10"
            IMAGE_TAG: "7.10.2"
          - BUILD_TAG: "6.8"
            IMAGE_TAG: "6.8.18"
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: mirror.gcr.io/tonistiigi/binfmt:latest

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - uses: supplypike/setup-bin@v4
        with:
          uri: https://github.com/hairyhenderson/gomplate/releases/latest/download/gomplate_linux-amd64
          name: gomplate
          version: latest

      - name: Generate Dockerfile
        run: gomplate -f images/elasticsearch/tpl.Dockerfile -o images/elasticsearch/Dockerfile
        env:
          IMAGE_TAG: ${{ matrix.IMAGE_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: images/elasticsearch/context
          file: images/elasticsearch/Dockerfile
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ vars.DOCKER_REPO }}/elasticsearch:${{ matrix.BUILD_TAG }}
          cache-from: type=registry,ref=${{ vars.DOCKER_REPO }}/elasticsearch:${{ matrix.BUILD_TAG }}
          cache-to: type=inline
