# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "Node Production • Docker Build"
on:
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - .github/workflows/docker-build-node-prod.yml
    branches:
      - main

jobs:
  node_prod:
    uses: ./.github/workflows/_service-build.yml
    secrets: inherit
    with:
      service: "node-prod"
      image: node
      tag_suffix: "-prod"
      build_contexts: |
        scripts-lib=images/_common/lib
        scripts-bin=images/_common/bin/node
      builds: |
        [
          {
            "build_tag": "latest",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "24"
            }
          },
          {
            "build_tag": "24",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "24"
            }
          },
          {
            "build_tag": "22",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "22"
            }
          },
          {
            "build_tag": "20",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "20"
            }
          },
          {
            "build_tag": "18",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "18"
            }
          },
          {
            "build_tag": "16",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "16"
            }
          },
          {
            "build_tag": "14",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "14"
            }
          },
          {
            "build_tag": "12",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "12"
            }
          },
          {
            "build_tag": "10",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "10"
            }
          }
        ]
