# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "Nginx • Docker Build"
on:
  schedule:
    - cron: "0 1 * * 6"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/nginx/**
      - .github/workflows/docker-build-nginx.yml
    branches:
      - main

jobs:
  nginx:
    uses: ./.github/workflows/_service-build.yml
    secrets: inherit
    with:
      service: nginx
      builds: |
        [
          {
            "build_tag": "1.28",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "1.28"
            }
          },
          {
            "build_tag": "latest",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "1.27"
            }
          },
          {
            "build_tag": "1.27",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "1.27"
            }
          },
          {
            "build_tag": "1.26",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "1.26"
            }
          }
        ]
