# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "Varnish • Docker Build"
on:
  schedule:
    - cron: "0 1 * * 6"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/varnish/**
      - .github/workflows/docker-build-varnish.yml
    branches:
      - main
jobs:
  build:
    name: "Build varnish"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - BUILD_TAG: "latest"
            VARNISH_VERSION: "7.7.2-1"
            VARNISH_REPO_VERSION: "77"
            VARNISH_MODULES_BRANCH: "7.7"
            DISTRO: "ubuntu"
            DISTRO_RELEASE: "noble"
            PLATFORMS: "linux/amd64,linux/arm64"
          - BUILD_TAG: "7.7"
            VARNISH_VERSION: "7.7.2-1"
            VARNISH_REPO_VERSION: "77"
            VARNISH_MODULES_BRANCH: "7.7"
            DISTRO: "ubuntu"
            DISTRO_RELEASE: "noble"
            PLATFORMS: "linux/amd64,linux/arm64"
          - BUILD_TAG: "6.0"
            VARNISH_VERSION: "6.0.13-1"
            VARNISH_REPO_VERSION: "60lts"
            VARNISH_MODULES_BRANCH: "6.0-lts"
            DISTRO: "ubuntu"
            DISTRO_RELEASE: "noble"
            PLATFORMS: "linux/amd64,linux/arm64"

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: mirror.gcr.io/tonistiigi/binfmt:latest

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - uses: supplypike/setup-bin@v4
        with:
          uri: https://github.com/hairyhenderson/gomplate/releases/latest/download/gomplate_linux-amd64
          name: gomplate
          version: latest

      - name: Generate Dockerfile
        run: gomplate -f images/varnish/tpl.Dockerfile -o images/varnish/Dockerfile
        env:
          VARNISH_VERSION: ${{ matrix.VARNISH_VERSION }}
          VARNISH_REPO_VERSION: ${{ matrix.VARNISH_REPO_VERSION }}
          VARNISH_MODULES_BRANCH: ${{ matrix.VARNISH_MODULES_BRANCH }}
          DISTRO: ${{ matrix.DISTRO }}
          DISTRO_RELEASE: ${{ matrix.DISTRO_RELEASE }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: images/varnish/context
          file: images/varnish/Dockerfile
          push: true
          platforms: ${{ matrix.PLATFORMS }}
          tags: |
            ${{ vars.DOCKER_REPO }}/varnish:${{ matrix.BUILD_TAG }}
            ${{ vars.DOCKER_REPO }}/varnish:${{ matrix.BUILD_TAG }}-${{ matrix.DISTRO }}
          cache-from: type=registry,ref=${{ vars.DOCKER_REPO }}/varnish:${{ matrix.BUILD_TAG }}-${{ matrix.DISTRO }}
          cache-to: type=inline
