# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "PHP-FPM Shopware Web • Docker Build"
on:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/template-docker-build-php-app-web.yml
    secrets: inherit
    with:
      app_name: "shopware-web"
      rootless: false
