# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "Magepack • Docker Build"
on:
  schedule:
    - cron: "0 1 * * 6"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/magepack/**
      - .github/workflows/docker-build-magepack.yml
    branches:
      - main

jobs:
  magepack:
    uses: ./.github/workflows/_service-build.yml
    secrets: inherit
    with:
      service: magepack
      builds: |
        [
          {
            "build_tag": "latest",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
            }
          },
          {
            "build_tag": "2.3",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
            }
          }
        ]
