# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "Valkey • Docker Build"
on:
  schedule:
    - cron: "0 1 * * 6"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/valkey/**
      - .github/workflows/docker-build-valkey.yml
    branches:
      - main

jobs:
  valkey:
    uses: ./.github/workflows/_service-build.yml
    secrets: inherit
    with:
      service: valkey
      builds: |
        [
          {
            "build_tag": "latest",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "9.0"
            }
          },
          {
            "build_tag": "9.0",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "9.0"
            }
          },
          {
            "build_tag": "8.1",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "8.1"
            }
          },
          {
            "build_tag": "8.0",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "8.0"
            }
          },
          {
            "build_tag": "7.2",
            "platforms": "linux/amd64,linux/arm/v7,linux/arm64",
            "args": {
              "IMAGE_TAG": "7.2"
            }
          }
        ]
