# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "MySQL • Docker Build"
on:
  schedule:
    - cron: "0 1 * * 6"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/mysql/**
      - .github/workflows/docker-build-mysql.yml
    branches:
      - main

jobs:
  mysql:
    uses: ./.github/workflows/_service-build.yml
    secrets: inherit
    with:
      service: mysql
      builds: |
        [
          {
            "build_tag": "latest",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "9.3"
            }
          },
          {
            "build_tag": "8.4",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "8.4"
            }
          },
          {
            "build_tag": "8.0",
            "platforms": "linux/amd64,linux/arm64",
            "args": {
              "IMAGE_TAG": "8.0"
            }
          }
        ]
