# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "PHP-FPM Rootless Magento 2 • Docker Build"
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    uses: ./.github/workflows/template-docker-build-php-app.yml
    secrets: inherit
    with:
      app_name: "magento2"
      rootless: true
