# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "Lint Dockerfiles"
on:
  push:
    paths:
      - images/**
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    name: "Lint Dockerfiles"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: supplypike/setup-bin@v5
        with:
          uri: https://github.com/hairyhenderson/gomplate/releases/latest/download/gomplate_linux-amd64
          name: gomplate
          version: latest

      - uses: supplypike/setup-bin@v5
        with:
          uri: https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          name: hadolint
          version: latest

      - name: Run Hadolint
        run: |
          set -euo pipefail
          find ./images -type f -name "tpl.Dockerfile" -print0 | xargs -I{} -0 /bin/bash -c "echo {}; hadolint <(gomplate -f {} -o - | sed '/--exclude/d' )"

# workaround for missing --exclude flag handling in hadolint
# https://github.com/hadolint/hadolint/issues/1029
#          find ./images -type f -name "tpl.Dockerfile" -print0 | xargs -I{} -0 /bin/bash -c "echo {}; hadolint <(gomplate -f {} -o -)"
