# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Docker Image Magepack
on:
  schedule:
    - cron: "0 6 1 * *"
  workflow_dispatch:
  push:
    paths:
      - images/.trigger
      - images/magepack/**
    branches:
      - main
jobs:
  magepack:
    name: magepack
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - BUILD_TAG: "latest"
            MAGEPACK_VERSION: "2.3"
          - BUILD_TAG: "2.3"
            MAGEPACK_VERSION: "2.3"
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
          config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]

      - uses: supplypike/setup-bin@v3
        with:
          uri: https://github.com/hairyhenderson/gomplate/releases/latest/download/gomplate_linux-amd64
          name: gomplate
          version: latest

      - name: Generate Dockerfile
        run: gomplate -f images/magepack/tpl.Dockerfile -o images/magepack/Dockerfile
        env:
          IMAGE_TAG: ${{ matrix.IMAGE_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: images/magepack/context
          file: images/magepack/Dockerfile
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: ${{ vars.DOCKER_REPO }}/magepack:${{ matrix.BUILD_TAG }}
          cache-from: type=registry,ref=${{ vars.DOCKER_REPO }}/magepack:${{ matrix.BUILD_TAG }}
          cache-to: type=inline
