---
name: Docker Image PHP-FPM Wordpress Web
on:
  workflow_run:
    workflows: [ "Docker Image PHP-FPM Wordpress" ]
    branches: [ main ]
    types:
      - completed
jobs:
  wordpress-web:
    name: Wordpress WEB - PHP-FPM ${{ matrix.php_version }} ${{ matrix.docker_base_images }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_base_images: [ "debian-bullseye", "ubuntu-jammy", "debian-bullseye-rootless" ]
        php_version: [ "7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2" ]
        build_group: [ "wordpress-web" ]
    #        include:
    #          - docker_base_images: "debian-bookworm"
    #            php_version: "8.0"
    #            build_group: "wordpress-web"
    #          - docker_base_images: "debian-bookworm"
    #            php_version: "8.1"
    #            build_group: "wordpress-web"
    #          - docker_base_images: "debian-bookworm"
    #            php_version: "8.2"
    #            build_group: "wordpress-web"
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
      - run: ./images/scripts/build.sh "${BUILD_GROUP}"
        env:
          BUILD_GROUP: php-fpm/${{ matrix.docker_base_images }}/${{ matrix.build_group }}
          PHP_VERSION: ${{ matrix.php_version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          PUSH: "true"
          DOCKER_USE_BUILDX: "true"
          DOCKER_BUILD_PLATFORM: "linux/amd64,linux/arm64"
