---
name: Docker Image Opensearch
on:
  schedule:
    - cron: "0 6 1 * *"
  push:
    paths:
      - images/.trigger
      - images/opensearch/**
    branches:
      - main
jobs:
  opensearch:
    name: Opensearch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
      - run: ./images/scripts/build.sh "${BUILD_GROUP}"
        env:
          BUILD_GROUP: opensearch
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          PUSH: "true"
          DOCKER_USE_BUILDX: "true"
          DOCKER_BUILD_PLATFORM: "linux/amd64,linux/arm64"
