---
name: Docker Image MySQL
on:
  schedule:
    - cron: "0 6 1 * *"
  push:
    paths:
      - images/.trigger
      - images/mysql/**
    branches:
      - main
jobs:
  mysql:
    name: MySQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./images/scripts/build.sh "${BUILD_GROUP}"
        env:
          BUILD_GROUP: mysql
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          PUSH: "true"
