# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: "Spelling"
on:
  push:
    branches:
      - "main"
  pull_request:
permissions:
  contents: "read"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  typos_check:
    name: "Check for typos in the repository"
    runs-on: "ubuntu-22.04"
    timeout-minutes: 1
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Search for misspellings"
        uses: crate-ci/typos@master
